### ISSUE TITLE
App crashes while headphones plugged in on mobile.

### ISSUE THREAD

**Issue by TLausZ** [digitalbitbox/bitbox-wallet-app#938]
My headphones are plugged in my USB-C port. I open the app and it crashes silently after half of a second.

App: Android-4.20.1
Android V10 on Pixel 3
Kernel version: 
4.9.210-g28c696160049-ab6386370
#0 Fri Apr 10 23:00:22 UTC 2020

**Comment by benma** [comment]
Interesting :thinking: 

What kind of headphones are they? Brand/model.

**Comment by x1ddos** [comment]
Reproduced on Moto g7play Android 9, latest app v4.40.1. Here's what I see in adb logcat:

```
07-25 15:12:55.072  8608  8608 D ch.shiftcrypto.bitboxapp: XYZ: lifecycle: onCreate
07-25 15:12:55.370  1924  1967 I ActivityManager: Start proc 8629:com.android.chrome:webview_service/u0a139 for service com.android.chrome/org.chromium.android_webview.services.VariationsSeedServer
07-25 15:12:55.449  1924  1967 I ActivityManager: Start proc 8645:com.android.chrome:sandboxed_process0/u0i51 for webview_service ch.shiftcrypto.bitboxapp/org.chromium.content.app.SandboxedProcessService0
07-25 15:12:56.070  8608  8682 I GoLog   : Logging configuration taken from '/data/user/0/ch.shiftcrypto.bitboxapp/files/logging.json'.
07-25 15:12:56.071  8608  8682 I GoLog   : Logging into '/data/user/0/ch.shiftcrypto.bitboxapp/files/log.txt' from 'debug'.
07-25 15:12:56.071  8608  8608 I GoLog   : time="2020-07-25T13:12:56Z" level=info msg="--------------- Started application --------------" group=server
07-25 15:12:56.071  8608  8608 I GoLog   : <nil>
07-25 15:12:56.072  8608  8608 I GoLog   : time="2020-07-25T13:12:56Z" level=info msg=environment goarch=arm goos=android group=server version=4.20.1
07-25 15:12:56.072  8608  8608 I GoLog   : <nil>
07-25 15:12:56.073  8608  8608 I GoLog   : time="2020-07-25T13:12:56Z" level=info msg="Arguments: &{mainDirectoryPath:/data/user/0/ch.shiftcrypto.bitboxapp/files bitbox02DirectoryPath:/data/user/0/ch.shiftcrypto.bitboxapp/files/bitbox02 bitboxBaseDirectoryPath:/data/user/0/ch.shiftcrypto.bitboxapp/files/bitboxBase cacheDirectoryPath:/data/user/0/ch.shiftcrypto.bitboxapp/files/cache appConfigFilename:/data/user/0/ch.shiftcrypto.bitboxapp/files/config.json accountsConfigFilename:/data/user/0/ch.shiftcrypto.bitboxapp/files/accounts.json testing:false regtest:false devmode:false devservers:false gapLimits:<nil> log:0x4fb7e800}" group=arguments
07-25 15:12:56.073  8608  8608 I GoLog   : <nil>
07-25 15:12:56.077  8608  8608 I GoLog   : time="2020-07-25T13:12:56Z" level=info msg="backend config: {Proxy:{UseProxy:false ProxyAddress:127.0.0.1:9050} Services:{Safello:true} BitcoinActive:true LitecoinActive:true EthereumActive:true SplitAccounts:false BTC:{ElectrumServers:[0x4f929800 0x4f929820]} TBTC:{ElectrumServers:[0x4f929840 0x4f929860]} RBTC:{ElectrumServers:[0x4f929880]} LTC:{ElectrumServers:[0x4f9298a0 0x4f9298c0]} TLTC:{ElectrumServers:[0x4f9298e0 0x4f929900]} ETH:{NodeURL:etherscan+https://api.etherscan.io/api TransactionsSource:etherScan ActiveERC20Tokens:[]} TETH:{NodeURL:etherscan+https://api-ropsten.etherscan.io/api TransactionsSource:etherScan ActiveERC20Tokens:[]} RETH:{NodeURL:etherscan+https://api-rinkeby.etherscan.io/api TransactionsSource:etherScan ActiveERC20Tokens:[]}}" group=backend
07-25 15:12:56.077  8608  8608 I GoLog   : <nil>
07-25 15:12:56.078  8608  8608 I GoLog   : time="2020-07-25T13:12:56Z" level=info msg="frontend config: map[guideShown:false userLanguage:<nil>]" group=backend
07-25 15:12:56.078  8608  8608 I GoLog   : <nil>
07-25 15:12:56.162  8608  8608 D ch.shiftcrypto.bitboxapp: XYZ: lifecycle: onStart
07-25 15:12:56.163  8608  8608 D ch.shiftcrypto.bitboxapp: XYZ: lifecycle: onResume
07-25 15:12:56.379  1924  1995 I ActivityManager: Displayed ch.shiftcrypto.bitboxapp/.MainActivity: +1s439ms
07-25 15:12:56.411  8608  8608 D ch.shiftcrypto.bitboxapp: XYZ: Uncaught TypeError: window.onAndroidPushNotification is not a function -- From line 1 of file:///android_asset/web/index.html
07-25 15:12:56.413  1110  2193 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen ch.shiftcrypto.bitboxapp#0
07-25 15:12:56.413  1110  2193 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen ch.shiftcrypto.bitboxapp#0
07-25 15:12:56.634  8608  8680 I GoLog   : time="2020-07-25T13:12:56Z" level=debug msg="Checking API token" group=handlers path=/api/config
07-25 15:12:56.634  8608  8680 I GoLog   : <nil>
07-25 15:12:56.639  8608  8680 I GoLog   : time="2020-07-25T13:12:56Z" level=debug msg="Checking API token" group=handlers path=/api/config
07-25 15:12:56.639  8608  8680 I GoLog   : <nil>
07-25 15:12:56.640  8608  8692 I GoLog   : time="2020-07-25T13:12:56Z" level=debug msg="Checking API token" group=handlers path=/api/rates
07-25 15:12:56.640  8608  8692 I GoLog   : <nil>
07-25 15:12:56.709  8608  8686 I GoLog   : time="2020-07-25T13:12:56Z" level=debug msg="Checking API token" group=handlers path=/api/config
07-25 15:12:56.709  8608  8686 I GoLog   : <nil>
07-25 15:12:56.713  8608  8686 I GoLog   : time="2020-07-25T13:12:56Z" level=debug msg="Checking API token" group=handlers path=/api/native-locale
07-25 15:12:56.713  8608  8686 I GoLog   : <nil>
07-25 15:12:56.717  8608  8686 I GoLog   : time="2020-07-25T13:12:56Z" level=debug msg="Checking API token" group=handlers path=/api/native-locale
07-25 15:12:56.717  8608  8686 I GoLog   : <nil>
07-25 15:12:56.723  8608  8686 I GoLog   : time="2020-07-25T13:12:56Z" level=debug msg="Checking API token" group=handlers path=/api/accounts
07-25 15:12:56.723  8608  8686 I GoLog   : <nil>
07-25 15:12:56.724  8608  8686 I GoLog   : time="2020-07-25T13:12:56Z" level=debug msg="Checking API token" group=handlers path=/api/devices/registered
07-25 15:12:56.724  8608  8686 I GoLog   : <nil>
07-25 15:12:56.727  8608  8686 I GoLog   : time="2020-07-25T13:12:56Z" level=debug msg="Checking API token" group=handlers path=/api/config
07-25 15:12:56.727  8608  8686 I GoLog   : <nil>
07-25 15:12:56.745  8608  8686 I GoLog   : time="2020-07-25T13:12:56Z" level=debug msg="Checking API token" group=handlers path=/api/bitboxbases/registered
07-25 15:12:56.745  8608  8686 I GoLog   : <nil>
07-25 15:12:56.746  8608  8686 I GoLog   : time="2020-07-25T13:12:56Z" level=debug msg="Checking API token" group=handlers path=/api/bitboxbases/detected
07-25 15:12:56.746  8608  8686 I GoLog   : <nil>
07-25 15:12:56.770  8608  8686 I GoLog   : time="2020-07-25T13:12:56Z" level=debug msg="Checking API token" group=handlers path=/api/version
07-25 15:12:56.770  8608  8686 I GoLog   : <nil>
07-25 15:12:56.774  8608  8686 I GoLog   : time="2020-07-25T13:12:56Z" level=debug msg="Checking API token" group=handlers path=/api/using-mobile-data
07-25 15:12:56.774  8608  8686 I GoLog   : <nil>
07-25 15:12:56.777  8608  8686 I GoLog   : time="2020-07-25T13:12:56Z" level=debug msg="Checking API token" group=handlers path=/api/banners/bitbox01
07-25 15:12:56.777  8608  8686 I GoLog   : <nil>
07-25 15:12:56.778  8608  8686 I GoLog   : time="2020-07-25T13:12:56Z" level=debug msg="Checking API token" group=handlers path=/api/update
07-25 15:12:56.778  8608  8686 I GoLog   : <nil>
07-25 15:12:56.780  8608  8712 I GoLog   : time="2020-07-25T13:12:56Z" level=debug msg="Checking API token" group=handlers path=/api/keystores
07-25 15:12:56.780  8608  8712 I GoLog   : <nil>
07-25 15:12:56.786  8608  8712 I GoLog   : time="2020-07-25T13:12:56Z" level=debug msg="Checking API token" group=handlers path=/api/config
07-25 15:12:56.786  8608  8712 I GoLog   : <nil>
07-25 15:12:59.816  1924  8732 W ActivityManager:   Force finishing activity ch.shiftcrypto.bitboxapp/.MainActivity
07-25 15:12:59.821  1924  8732 D ActivityManager: found next focusableStack ActivityStack{2857feb stackId=0 type=home mode=fullscreen visible=true translucent=true, 1 tasks} with top ActivityRecord{5bf914a u0 com.motorola.launcher3/com.android.launcher3.CustomizationPanelLauncher t2} as current stack ActivityStack{dab907d stackId=113 type=standard mode=fullscreen visible=true translucent=true, 1 tasks}
07-25 15:12:59.839  1924  8732 W ActivityManager: Exception thrown during pause
07-25 15:12:59.839  1924  8732 W ActivityManager: android.os.DeadObjectException
07-25 15:12:59.839  1924  8732 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
07-25 15:12:59.839  1924  8732 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:1136)
07-25 15:12:59.839  1924  8732 W ActivityManager: 	at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:1807)
07-25 15:12:59.839  1924  8732 W ActivityManager: 	at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:129)
07-25 15:12:59.839  1924  8732 W ActivityManager: 	at com.android.server.am.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
07-25 15:12:59.839  1924  8732 W ActivityManager: 	at com.android.server.am.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:69)
07-25 15:12:59.839  1924  8732 W ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1489)
07-25 15:12:59.839  1924  8732 W ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3835)
07-25 15:12:59.839  1924  8732 W ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3774)
07-25 15:12:59.839  1924  8732 W ActivityManager: 	at com.android.server.am.ActivityStack.finishTopCrashedActivityLocked(ActivityStack.java:3652)
07-25 15:12:59.839  1924  8732 W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopCrashedActivitiesLocked(ActivityStackSupervisor.java:2370)
07-25 15:12:59.839  1924  8732 W ActivityManager: 	at com.android.server.am.AppErrors.handleAppCrashLocked(AppErrors.java:750)
07-25 15:12:59.839  1924  8732 W ActivityManager: 	at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:582)
07-25 15:12:59.839  1924  8732 W ActivityManager: 	at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:450)
07-25 15:12:59.839  1924  8732 W ActivityManager: 	at com.android.server.am.AppErrors.crashApplication(AppErrors.java:395)
07-25 15:12:59.839  1924  8732 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:16021)
07-25 15:12:59.839  1924  8732 W ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:85)
07-25 15:12:59.854  1924  2220 W InputDispatcher: channel '2ceaf37 ch.shiftcrypto.bitboxapp/ch.shiftcrypto.bitboxapp.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-25 15:12:59.854  1924  2220 E InputDispatcher: channel '2ceaf37 ch.shiftcrypto.bitboxapp/ch.shiftcrypto.bitboxapp.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-25 15:12:59.941   960   960 I Zygote  : Process 8608 exited due to signal (6)
07-25 15:12:59.971  1924  3532 I WindowManager: WIN DEATH: Window{2ceaf37 u0 ch.shiftcrypto.bitboxapp/ch.shiftcrypto.bitboxapp.MainActivity}
07-25 15:12:59.971  1924  3532 W InputDispatcher: Attempted to unregister already unregistered input channel '2ceaf37 ch.shiftcrypto.bitboxapp/ch.shiftcrypto.bitboxapp.MainActivity (server)'
```

**Comment by x1ddos** [comment]
Here's some more with unflitered logs:

```
07-25 15:17:47.512  9061  9127 I GoLog   : time="2020-07-25T13:17:47Z" level=debug msg="Checking API token" group=handlers path=/api/config
07-25 15:17:47.512  9061  9127 I GoLog   : <nil>
07-25 15:17:47.990  9061     0 E Go      : panic: unrecognized device
07-25 15:17:47.990  9061     0 E Go      :
07-25 15:17:47.990  9061     0 E Go      : goroutine 45 [running]:
07-25 15:17:47.990  9061     0 E Go      : github.com/digitalbitbox/bitbox-wallet-app/backend/devices/usb.(*Manager).listen(0x4fe13ec0)
07-25 15:17:47.990  9061     0 E Go      : 	/opt/go/src/github.com/digitalbitbox/bitbox-wallet-app/backend/devices/usb/manager.go:310 +0xa04
07-25 15:17:47.990  9061     0 E Go      : created by github.com/digitalbitbox/bitbox-wallet-app/backend/devices/usb.(*Manager).Start
07-25 15:17:47.990  9061     0 E Go      : 	/opt/go/src/github.com/digitalbitbox/bitbox-wallet-app/backend/devices/usb/manager.go:323 +0x30
```

Hello, panic!

**Comment by x1ddos** [comment]
TBH though the app is kind of useless without the device plugged in :)
But of course that's not an excuse to panic. We'll fix it.
